### ISSUE TITLE
Finalise the database models

### ISSUE THREAD

**Issue by ShashinGounden** [COS301-SE-2023/Pronto#27]
Please finalize the database models, updating any changes that needs to be made.

**Comment by Bandisa** [comment]
# Update 
1. There was an issue with deployment, specifically, some policies for the amplify-dev IAM roles had to be modified. 
2. We also made the mistake of looking at the [V1 GraphQL transformer documentation](https://docs.amplify.aws/cli-legacy/graphql-transformer/key/) instead of [V2](https://docs.amplify.aws/cli/graphql/data-modeling/). So tomorrow we will adjust the schema with the new keywords and test.
3. Upon research, with the lesson from the issue above, I found that `amplify api gql-compile` will enable us to test our schema without having to actually deploy. So that will be incorporated to our workflow accordingly. 

Me & @u20612894  will address the issues above and provide updates accordingly.

**Comment by Bandisa** [comment]
# Update
Data models have been updated to the lates version
# Next step
I will be adding auth rules to the models

**Comment by ShashinGounden** [comment]
Completed and up.
